### ISSUE TITLE
Upcoming setuptools release breaks package build

### ISSUE THREAD

**Issue by jsivak** [JarryShaw/lorem#105]
Looks like a "breaking change" is being introduced by setuptools on 2024-Sep-26:

`  Collecting python_lorem (from -r requirements\application.txt (line 188))
    Using cached http://devpi.escalent.co/root/pypi/%2Bf/6a8/90b0ae42aea21/python-lorem-1.3.0.post1.tar.gz (11 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... error
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [72 lines of output]
        C:\Users\jsivak\AppData\Local\Temp\pip-build-env-47l9ocw9\overlay\Lib\site-packages\setuptools\dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
        !!

                ********************************************************************************
                Usage of dash-separated 'description-file' will not be supported in future
                versions. Please use the underscore name 'description_file' instead.

                By 2024-Sep-26, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.

                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************

        !!`

**To Reproduce**

1. In a virtual environment: Install setuptools 70.1.0
2. Uninstall pyton-lorem if already installed.
3. Install python-lorem

I'm guessing that the offending config setting is the "description-file" setting in the setup.cfg file.

**Comment by adambirds** [comment]
I'm getting this too, can this be fixed asap?
