### ISSUE TITLE
Allow for word pool on all API calls

### ISSUE THREAD

**Issue by kesmit13** [JarryShaw/lorem#53]
I've started using this project for a data generator for a database. One feature that I need is for it to be able to generate text with various encodings for different columns. This would require each data generator function to have its own word pool. Right now the word pool is a global, so I have to generate a column-at-a-time rather than a row-at-a-time which is needed for large data sets. Is there any chance a more configurable word pool could be incorporated?

**Comment by JarryShaw** [comment]
Well noted. Added the support to use seperate word pool thru a revised internal class in version 1.2.0

For more info, pls refer to the documentation.
