### ISSUE TITLE
Incorrect Tuple typing

### ISSUE THREAD

**Issue by philer-jambit** [JarryShaw/lorem#55]
The `get_word` function has a `count` as its first parameter with the type `int | Tuple[int]`. However, since tuples have a fixed length, unlike for `List`, in the `Tuple` type multiple possible entries need their own types. Since the tuple version of the parameter takes two parameters (min and max), that type should be `Tuple[int, int]`.

For example replace
```py
def get_word(count: typing.Union[int, typing.Tuple[int]] = 1,
```
with
```py
def get_word(count: typing.Union[int, typing.Tuple[int, int]] = 1,
```

There are more instances of this, such as the `comma` parameter in `get_sentence`. These are also mentioned in the README.

**Comment by JarryShaw** [comment]
Fixed.
