### ISSUE TITLE
Mark arguments as keyword only

### ISSUE THREAD

**Issue by philer-jambit** [JarryShaw/lorem#60]
In 1.2.0 the usual `get_*` functions got an additional parameter which was added at the front. This caused our code to break in what we expected to be a safe batch upgrade as we were relying on positional arguments.

Following semantic versioning helps prevent such surprises. In a minor version new parameters could still be added at the end (if they are optional).

To ensure that your functions only get called with keyword arguments I suggest to enforce it like `def get_words(*, ...):`.

**Comment by ThomDietrich** [comment]
Also/alternatively please think about the arrangement of your parameters. The code snippet `lorem.get_words(5)` feels very intuitive, but it's answered by an ugly error message.

Even worse: The new `pool` parameter is not documented here: https://jarryshaw.github.io/lorem/

**Comment by JarryShaw** [comment]
Thanks for all your ideas and inputs! I've moved `pool` as a keyword-only argument in 1.3.0 and the rest arguments are kept in their originally intuitive way.
